name: electricity_counter_mastr_copy  
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.20.1
  pull_down_button: ^0.10.2
  uni_links: ^0.5.1
  url_launcher: ^6.3.1
  logger: ^1.0.0  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/dark_background2.jpg
    - assets/images/light_background2.jpg
    - assets/icons/light_button2.png
    - assets/icons/dark_button2.png
    - assets/default_avatar.png
    

